services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madnezz-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - madnezz-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=madnezz_db
      - DB_USERNAME=madnezz_user
      - DB_PASSWORD=madnezz_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  webserver:
    image: nginx:alpine
    container_name: madnezz-api-webserver
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - madnezz-network

  db:
    image: postgres:16
    container_name: madnezz-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: madnezz_db
      POSTGRES_USER: madnezz_user
      POSTGRES_PASSWORD: madnezz_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U madnezz_user -d madnezz_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - madnezz-network

  redis:
    image: redis:7-alpine
    container_name: madnezz-api-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - madnezz-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madnezz-api-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - madnezz-network
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=madnezz_db
      - DB_USERNAME=madnezz_user
      - DB_PASSWORD=madnezz_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres_data:
  redis_data:

networks:
  madnezz-network:
    driver: bridge